/**
 * @description 세션스토리지 키 관리
 */
export const STORAGE_KEYS = {
  RECENT_MENU_ITEMS: 'RECENT_MENU_ITEMS',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  AX_ACCESS_TOKEN: 'AX_ACCESS_TOKEN',
  // expires_at 기반 만료 관리용 키
  EXPIRES_AT: 'EXPIRES_AT',
  // 세션에서 관리하는 유저
  SESSION_USERNAME: 'USERNAME',
  // 검색 조건
  SEARCH_VALUES: {
    DEFAULT: 'DEFAULT',
    MODEL_CTLG_LIST: 'MODEL_CTLG_LIST',
    MODEL_CTLG_DETAIL: 'MODEL_CTLG_DETAIL',
    FEW_SHOT_LIST: 'FEW_SHOT_LIST',
    AGENT_TOOL_LIST: 'AGENT_TOOL_LIST',
    DATA_TOOL_LIST: 'DATA_TOOL_LIST',
    VECTOR_DB_LIST: 'VECTOR_DB_LIST',
    DATA_CTLG_LIST: 'DATA_CTLG_LIST',
    DEPLOY_API_KEY_LIST: 'DEPLOY_API_KEY_LIST',
    API_KEY_MGMT_LIST: 'API_KEY_MGMT_LIST',
    MODEL_DEPLOY_LOG_LIST: 'MODEL_DEPLOY_LOG_LIST',
    AGENT_DEPLOY_LOG_LIST: 'AGENT_DEPLOY_LOG_LIST',
    MODEL_GARDEN_LIST_SELF_HOSTING: 'MODEL_GARDEN_LIST_SELF_HOSTING',
    MODEL_GARDEN_LIST_SERVERLESS: 'MODEL_GARDEN_LIST_SERVERLESS',
    MODEL_GARDEN_LIST_TAB: 'MODEL_GARDEN_LIST_TAB',
    MODEL_DEPLOY_MON: 'MODEL_DEPLOY_MON',
    AGENT_DEPLOY_MON: 'AGENT_DEPLOY_MON',
    AGENT_MCP_CTLG_LIST: 'AGENT_MCP_CTLG_LIST',
    DEPLOY_AGENT_LIST: 'DEPLOY_AGENT_LIST',
    WORKFLOW_LIST: 'WORKFLOW_LIST',
    INFERENCE_PROMPT_LIST: 'INFERENCE_PROMPT_LIST',
    GUARDRAIL_PROMPT_LIST: 'GUARDRAIL_PROMPT_LIST',
    KNOWLEDGE_LIST: 'KNOWLEDGE_LIST',
    KNOWLEDGE_MD_LIST: 'KNOWLEDGE_MD_LIST',
    DATA_SET_LIST: 'DATA_SET_LIST',
    TRAINING_DATA_LIST: 'TRAINING_DATA_LIST',
    EVALUATION_DATA_LIST: 'EVALUATION_DATA_LIST',
    MD_PACKAGE_LIST: 'MD_PACKAGE_LIST',
    EVAL_LIST: 'EVAL_LIST',
    GUARDRAIL_MAIN_TAB: 'GUARDRAIL_MAIN_TAB',
    AGENT_BUILDER_LIST: 'AGENT_BUILDER_LIST',
    SAFETY_FILTER_LIST: 'SAFETY_FILTER_LIST',
    MODEL_FINETUNING_LIST: 'MODEL_FINETUNING_LIST',
    USER_USAGE_HIST_LIST: 'USER_USAGE_HIST_LIST',
    USER_USAGE_HIST_DETAIL: 'USER_USAGE_HIST_DETAIL',
    NOTICE_MGMT_LIST: 'NOTICE_MGMT_LIST',
    NOTICE_MGMT_DETAIL_NOTI_ID: 'NOTICE_MGMT_DETAIL_NOTI_ID',
    API_KEY_MGMT_DETAIL_ID: 'API_KEY_MGMT_DETAIL_ID',

    // 관리 페이지 - 탭 상태
    PROJ_DETAIL_TAB: 'PROJ_DETAIL_TAB',
    PROJ_ROLE_DETAIL_TAB: 'PROJ_ROLE_DETAIL_TAB',

    // 관리 페이지 - 폼 입력값
    USER_LIST_FORM: 'USER_LIST_FORM',
    USER_PROJ_LIST_FORM: 'USER_PROJ_LIST_FORM',
    PROJ_LIST_FORM: 'PROJ_LIST_FORM',
    PROJ_ROLE_LIST_FORM: 'PROJ_ROLE_LIST_FORM',
    PROJ_USER_LIST_FORM: 'PROJ_USER_LIST_FORM',
    PROJ_ROLE_USER_LIST_FORM: 'PROJ_ROLE_USER_LIST_FORM',
    PROJ_ROLE_PERMISSION_LIST_FORM: 'PROJ_ROLE_PERMISSION_LIST_FORM',
    IDE_IMAGE_LIST_FORM: 'IDE_IMAGE_LIST_FORM',

    // 관리 페이지 - API 파라미터
    USER_LIST_PARAMS: 'USER_LIST_PARAMS',
    USER_PROJ_LIST_PARAMS: 'USER_PROJ_LIST_PARAMS',
    PROJ_LIST_PARAMS: 'PROJ_LIST_PARAMS',
    PROJ_ROLE_LIST_PARAMS: 'PROJ_ROLE_LIST_PARAMS',
    PROJ_USER_LIST_PARAMS: 'PROJ_USER_LIST_PARAMS',
    PROJ_ROLE_USER_LIST_PARAMS: 'PROJ_ROLE_USER_LIST_PARAMS',
    PROJ_ROLE_PERMISSION_LIST_PARAMS: 'PROJ_ROLE_PERMISSION_LIST_PARAMS',
    IDE_IMAGE_LIST_PARAMS: 'IDE_IMAGE_LIST_PARAMS',
  },
} as const;
