export const MODAL_ID = {
  MOLIMATE_LOGIN_MODAL: 'MOLIMATE_LOGIN_MODAL',
  SWING_LOGIN_MODAL: 'SWING_LOGIN_MODAL',
  SWING_SMS_MODAL: 'SWING_SMS_MODAL',
  TEST_CONTROL_SMALL: 'TEST_CONTROL_SMALL',
  TEST_CONTROL_CONFIRM: 'TEST_CONTROL_CONFIRM',
  MODEL_FINETUNING_DATASET_SELECTION: 'MODEL_FINETUNING_DATASET_SELECTION',
  MODEL_FINETUNING_METRICS_SELECTION: 'MODEL_FINETUNING_METRICS_SELECTION',
  API_KEY_ISSUE: 'API_KEY_ISSUE',
  MODEL_PLAYGROUND_PROMPT_SELECTION: 'MODEL_PLAYGROUND_PROMPT_SELECTION',
  MODEL_PLAYGROUND_MODEL_SELECTION: 'MODEL_PLAYGROUND_MODEL_SELECTION',
  SET_MODEL_PARAM: 'SET_MODEL_PARAM',
  MODEL_GARDEN_DOIP_RESULT_POPUP: 'MODEL_GARDEN_DOIP_RESULT_POPUP',
} as const;
